version: '3'

services:
  front:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 4200:4200
    network_mode: "host"
    env_file:
      - envs/.dev.env
